export const BASE_URL = 'http://localhost:8080/'
export const POST = 'post/'
export const PAGE = 'page/'
export const SEARCH = 'search/'
export const COMMENT = 'comment/'
export const PICTURE = '/picture'

export const ADD_POST = 'Add post'
export const ADD_COMMENT = 'Add comment'
export const EDIT = 'edit'
